### PR TITLE
Design changes in Home.html and home.css

### PR DESCRIPTION
**Pull request by oneofthedevs**
So I made a few changes in Home.html and it's respective css file, made it a bit more mobile friendly and overall a little modern feel. Hope you'll like it 👍

### CODE REVIEW

**Comment by Aagam-Jain-113** [comment]
I have looked over your changes. Few suggestions if you can do it:

- Fix notification bell icon 

- Make Create Post button more distinct

- Make it dynamic For eg: You can't create a new post in this. After clicking Create Post button you must be able to see the post in recent posts

- Remove the image that is inserted

**Comment by oneofthedevs** [comment]
I will look into that but I just want to know who wrote the front-end originally, no offense but the code is just so cluttered and messed up it took me like 2-3 hours to do something that I could probably finish in like 1.  
Now, going through each point,

1. What exactly needs to be fixed? 
2. By distinct you mean bigger or something, cause I kept it that way so it doesn't conflict with your original colour scheme or intended design.  
3. The data isn't exactly coming from a database or anything (it's just static HTML hardcoded), so not sure how I can make it dynamic
4. The image is there because without it the form will take up the entire width of the page and it won't look good on desktop, but sure I will look into it

**Comment by oneofthedevs** [comment]
Can you please accept this pull request first?

**Comment by Aagam-Jain-113** [comment]
We know our code is cluttered as it was written by a beginner So if you can reformat our code you can create a new issue 

1. & 2. We want a new design which is interactive and minimalistic 

3. If you can use firebase to store data ? 

4. Okay!

**Comment by oneofthedevs** [comment]
1. Alright I will think of something

2. Can you make one and integrate in the app, cause I don't have much experience in backend 

3. Can you please accept this PR first?

**Pull request merged**
